"""empty message

Revision ID: c4c893f9f1f0
Revises: c45e279b7a4c
Create Date: 2020-02-12 23:42:30.776348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4c893f9f1f0'
down_revision = 'c45e279b7a4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todo', sa.Column('completed', sa.Boolean(), nullable=True))

    op.execute('UPDATE todo SET completed = FALSE WHERE completed is NULL;')

    op.alter_column('todo', 'completed', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todo', 'completed')
    # ### end Alembic commands ###
